# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewsAPI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewsAPI
  pod 'SDWebImage', '~> 5.0'

  target 'NewsAPITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewsAPIUITests' do
    # Pods for testing
  end

end
